[package]
name = "sat"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
description = "A performance-oriented incremental SAT and SMT solver written in Rust"
license = "MIT"
publish = false
default-run = "sat"

[dependencies]
num-bigint = "0.4"
num-rational = "0.4"
num-traits = "0.2"

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"

[profile.profiling]
inherits = "release"
debug = true
strip = "none"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all = { level = "warn", priority = -1 }
allow_attributes_without_reason = "deny"
dbg_macro = "deny"
todo = "deny"
unimplemented = "deny"

[lints.rustdoc]
broken_intra_doc_links = "deny"
